### ISSUE TITLE
Integrate Error Data

### ISSUE THREAD

**Issue by CoryK8nn8dy** [RedRocksCommunityCollege/Elevation-Descent#3]
Find the area under the curve for all three model's difference histogram results. Consult with @AForland on the mathematics if the code implementation isn't obvious.

**Comment by CoryK8nn8dy** [comment]
UPDATE: seems like exponentiating the data before taking it's derivative would serve to penalize greater error magnitudes

**Comment by CoryK8nn8dy** [comment]
First attempt at exponentiating/cubing error data arrays produced unexpected results when attempting to re-plot them in a histogram.

**Comment by AForland** [comment]
Try a quadratic here. That should reflect the correct penalty that we are looking for.

**Comment by CoryK8nn8dy** [comment]
These efforts are being abandoned in light of new approaches at accurizing our grade profiles.
