### ISSUE TITLE
Data directory cleanup

### ISSUE THREAD

**Issue by AForland** [RedRocksCommunityCollege/Elevation-Descent#7]
Can we move the last few files that are not in directories in the top level of the data directory. I am not sure exactly where they should go, but nothing from curve_fitting is pointing to them.

**Comment by CoryK8nn8dy** [comment]
Created appropriate sub-directories for homeless data files and updated file paths in jupyter notebooks to match. Commits c4b320a and 9fc4590. Closing issue.
